"""ORM model registry.

Importing this package registers every model on ``Base.metadata``. Alembic's
``env.py`` imports it so that autogenerate sees the full schema -- when you add
a new model, export it here.
"""

from app.models.announcement import Announcement, AnnouncementAcknowledgement
from app.models.app_setting import AppSetting
from app.models.asset import (
    Asset,
    AssetAssignment,
    AssetCategory,
    AssetHistory,
    AssetMaintenance,
    AssetReturn,
    AssetTransfer,
)
from app.models.audit_log import AuditAction, AuditLog, AuditOutcome
from app.models.business_unit import BusinessUnit
from app.models.designation import Designation
from app.models.document import Document, DocumentVersion
from app.models.document_category import DocumentCategory, DocumentType
from app.models.employee import Employee
from app.models.employee_address import EmployeeAddress
from app.models.employee_bank_detail import EmployeeBankDetail
from app.models.employee_identification import EmployeeIdentification
from app.models.employment_history import EmployeeEmploymentHistory
from app.models.employment_type import EmploymentType
from app.models.enums import (
    AddressType,
    BloodGroup,
    DocumentOwnerType,
    DocumentStatus,
    EmploymentChangeType,
    EmploymentStatus,
    Gender,
    MaritalStatus,
    RecordStatus,
    WorkMode,
)
from app.models.grade import Grade
from app.models.helpdesk import (
    HelpdeskCategory,
    HelpdeskComment,
    HelpdeskHistory,
    HelpdeskTicket,
)
from app.models.interview import (
    Interview,
    InterviewAttachment,
    InterviewFeedback,
    InterviewPanel,
    InterviewScheduleHistory,
    InterviewScore,
)
from app.models.location import Location
from app.models.offboarding import (
    AccessClearance,
    AssetClearance,
    ExitDocument,
    ExitInterview,
    FinalSettlementTracking,
    HandoverRecord,
    OffboardingCase,
    OffboardingTask,
    Resignation,
    ResignationHistory,
)
from app.models.offer import (
    Offer,
    OfferApproval,
    OfferSalaryComponent,
    OfferStatusHistory,
    OfferTemplate,
    OfferVersion,
)
from app.models.onboarding import (
    OnboardingCase,
    OnboardingHistory,
    OnboardingTask,
    PolicyAcknowledgement,
    PreboardingProfile,
)
from app.models.organization import Organization
from app.models.payroll import (
    EmployeeCompensation,
    EmployeeCompensationComponent,
    PayrollAdjustment,
    PayrollApproval,
    PayrollConfiguration,
    PayrollConfigurationHistory,
    PayrollEmployeeRecord,
    PayrollEmployeeSetting,
    PayrollFinalSnapshot,
    PayrollInput,
    PayrollInputException,
    PayrollInputSource,
    PayrollLeaveRule,
    PayrollLineItem,
    PayrollPeriod,
    PayrollReviewChecklist,
    PayrollReviewComment,
    PayrollRun,
    PayrollRunException,
    Payslip,
    SalaryComponent,
    SalaryHistory,
    SalaryStructure,
    SalaryStructureComponent,
)
from app.models.payroll_settlement import (
    FinalSettlement,
    FinalSettlementAdjustment,
    FinalSettlementItem,
)
from app.models.performance import (
    ContinuousFeedback,
    FinalReview,
    Goal,
    GoalProgress,
    GoalRating,
    ManagerReview,
    PerformanceCycle,
    PerformanceHistory,
    Recognition,
    SelfReview,
)
from app.models.project import AllocationHistory, Client, EmployeeAllocation, Project, ProjectMember
from app.models.rbac import Permission, Role, RolePermission, UserRole
from app.models.recruitment import (
    Candidate,
    CandidateDocument,
    CandidateSkill,
    CandidateSource,
    CandidateStageHistory,
    CandidateTalentPool,
    JobOpening,
    RecruiterNote,
    RecruitmentStage,
    TalentPool,
)
from app.models.refresh_token import RefreshToken
from app.models.requisition import (
    JobRequisition,
    Notification,
    RequisitionApproval,
    RequisitionAttachment,
    RequisitionHistory,
)
from app.models.team import Team
from app.models.user import User
from app.models.workforce import (
    AttendanceRecord,
    AttendanceRegularization,
    EmployeeShift,
    Holiday,
    HolidayCalendar,
    LeaveBalance,
    LeaveRequest,
    LeaveType,
    Shift,
    Timesheet,
    TimesheetEntry,
)

__all__ = [
    "AccessClearance",
    "AddressType",
    "AllocationHistory",
    "Announcement",
    "AnnouncementAcknowledgement",
    "AppSetting",
    "Asset",
    "AssetAssignment",
    "AssetCategory",
    "AssetClearance",
    "AssetHistory",
    "AssetMaintenance",
    "AssetReturn",
    "AssetTransfer",
    "AttendanceRecord",
    "AttendanceRegularization",
    "AuditAction",
    "AuditLog",
    "AuditOutcome",
    "BloodGroup",
    "BusinessUnit",
    "Candidate",
    "CandidateDocument",
    "CandidateSkill",
    "CandidateSource",
    "CandidateStageHistory",
    "CandidateTalentPool",
    "Client",
    "ContinuousFeedback",
    "Designation",
    "Document",
    "DocumentCategory",
    "DocumentOwnerType",
    "DocumentStatus",
    "DocumentType",
    "DocumentVersion",
    "Employee",
    "EmployeeAddress",
    "EmployeeAllocation",
    "EmployeeBankDetail",
    "EmployeeCompensation",
    "EmployeeCompensationComponent",
    "EmployeeEmploymentHistory",
    "EmployeeIdentification",
    "EmployeeShift",
    "EmploymentChangeType",
    "EmploymentStatus",
    "EmploymentType",
    "ExitDocument",
    "ExitInterview",
    "FinalReview",
    "FinalSettlement",
    "FinalSettlementAdjustment",
    "FinalSettlementItem",
    "FinalSettlementTracking",
    "Gender",
    "Goal",
    "GoalProgress",
    "GoalRating",
    "Grade",
    "HandoverRecord",
    "HelpdeskCategory",
    "HelpdeskComment",
    "HelpdeskHistory",
    "HelpdeskTicket",
    "Holiday",
    "HolidayCalendar",
    "Interview",
    "InterviewAttachment",
    "InterviewFeedback",
    "InterviewPanel",
    "InterviewScheduleHistory",
    "InterviewScore",
    "JobOpening",
    "JobRequisition",
    "LeaveBalance",
    "LeaveRequest",
    "LeaveType",
    "Location",
    "ManagerReview",
    "MaritalStatus",
    "Notification",
    "OffboardingCase",
    "OffboardingTask",
    "Offer",
    "OfferApproval",
    "OfferSalaryComponent",
    "OfferStatusHistory",
    "OfferTemplate",
    "OfferVersion",
    "OnboardingCase",
    "OnboardingHistory",
    "OnboardingTask",
    "Organization",
    "PayrollAdjustment",
    "PayrollApproval",
    "PayrollConfiguration",
    "PayrollConfigurationHistory",
    "PayrollEmployeeRecord",
    "PayrollEmployeeSetting",
    "PayrollFinalSnapshot",
    "PayrollInput",
    "PayrollInputException",
    "PayrollInputSource",
    "PayrollLeaveRule",
    "PayrollLineItem",
    "PayrollPeriod",
    "PayrollReviewChecklist",
    "PayrollReviewComment",
    "PayrollRun",
    "PayrollRunException",
    "Payslip",
    "PerformanceCycle",
    "PerformanceHistory",
    "Permission",
    "PolicyAcknowledgement",
    "PreboardingProfile",
    "Project",
    "ProjectMember",
    "Recognition",
    "RecordStatus",
    "RecruiterNote",
    "RecruitmentStage",
    "RefreshToken",
    "RequisitionApproval",
    "RequisitionAttachment",
    "RequisitionHistory",
    "Resignation",
    "ResignationHistory",
    "Role",
    "RolePermission",
    "SalaryComponent",
    "SalaryHistory",
    "SalaryStructure",
    "SalaryStructureComponent",
    "SelfReview",
    "Shift",
    "TalentPool",
    "Team",
    "Timesheet",
    "TimesheetEntry",
    "User",
    "UserRole",
    "WorkMode",
]
