"""Team master -- the smallest unit of the organizational hierarchy."""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base
from app.db.mixins import AuditableBase
from app.models.mixins import NamedMasterMixin, status_check, unique_ci_scoped

if TYPE_CHECKING:
    from app.models.business_unit import BusinessUnit
    from app.models.user import User


class Team(Base, AuditableBase, NamedMasterMixin):
    """A team within a business unit.

    Teams carry no code: unlike the level above them they are not referenced by
    short identifier, and requiring one would be busywork for the people
    maintaining the data.
    """

    __tablename__ = "teams"
    __table_args__ = (
        unique_ci_scoped("uq_teams_business_unit_id_name_lower", "business_unit_id", "name"),
        status_check(),
        {"comment": "Teams within a business unit."},
    )

    business_unit_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("business_units.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    manager_id: Mapped[uuid.UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        # Points at `users` because the Employee module did not exist when this
        # was written. Changing it to `employees` is a migration, not a redesign,
        # because the column is already a nullable UUID reference rather than a
        # free-text name.
        #
        # `use_alter` because this is the edge that closes a cycle: a user sits
        # in a team, and a team is managed by a user. Without it SQLAlchemy
        # cannot sort the tables and drops *every* foreign key between them from
        # consideration, which would silently mis-order a future autogenerated
        # migration.
        ForeignKey("users.id", ondelete="SET NULL", use_alter=True),
        nullable=True,
        index=True,
        doc="Team manager. References users until the Employee module exists.",
    )

    business_unit: Mapped[BusinessUnit] = relationship(
        back_populates="teams",
        foreign_keys=[business_unit_id],
        lazy="joined",
    )
    manager: Mapped[User | None] = relationship(foreign_keys=[manager_id], lazy="joined")

    def __repr__(self) -> str:
        return f"<Team id={self.id} name={self.name!r}>"
