"""User management and self-service profile endpoints.

Two audiences share one router. The self-service routes sit under ``/users/me``
and are declared *before* ``/users/{user_id}``: Starlette matches in
registration order, so the reverse would let ``/{user_id}`` capture "me" and
fail to parse it as a UUID.

Every administrative route carries a ``users:*`` permission guard (RBAC,
Phase 15). The split between :class:`UserUpdate` and :class:`ProfileUpdate`
matters independently of the guards -- it is what stops a self-service request
carrying an organizational assignment even when a role check passes.

NOTE: no ``from __future__ import annotations`` -- FastAPI reads parameter types
from evaluated annotations, and postponed evaluation breaks ``Annotated[...,
Query()]`` on the list endpoint.
"""

import uuid
from typing import Annotated

from fastapi import APIRouter, Query, status

from app.api.deps import CurrentUser, UserSvc, require
from app.schemas.common import APIErrorResponse, APIResponse, Page
from app.schemas.user import (
    AdminPasswordReset,
    ProfileUpdate,
    UserCreate,
    UserListParams,
    UserRead,
    UserUpdate,
)

router = APIRouter(prefix="/users", tags=["Users"])

_COMMON_ERRORS: dict[int | str, dict[str, object]] = {
    status.HTTP_401_UNAUTHORIZED: {"model": APIErrorResponse, "description": "Not signed in."},
    status.HTTP_422_UNPROCESSABLE_CONTENT: {"model": APIErrorResponse, "description": "Validation failed."},
}
_NOT_FOUND: dict[int | str, dict[str, object]] = {
    status.HTTP_404_NOT_FOUND: {"model": APIErrorResponse, "description": "No such user."},
}
_CONFLICT: dict[int | str, dict[str, object]] = {
    status.HTTP_409_CONFLICT: {
        "model": APIErrorResponse,
        "description": "Duplicate identifier, or a referential or safety rule was violated.",
    },
}


# ----------------------------------------------------------------------
# Self service -- must precede /{user_id}
# ----------------------------------------------------------------------
@router.get(
    "/me",
    response_model=APIResponse[UserRead],
    summary="Get my profile",
    responses={**_COMMON_ERRORS},
)
async def get_my_profile(current_user: CurrentUser) -> APIResponse[UserRead]:
    return APIResponse.ok(UserRead.from_user(current_user), message="Profile retrieved successfully")


@router.patch(
    "/me",
    response_model=APIResponse[UserRead],
    summary="Update my profile",
    description=(
        "Updates the fields a user owns: personal email, mobile number and profile photo. "
        "Names, username, official email, organizational placement and status are "
        "administrative and are rejected here."
    ),
    responses={**_COMMON_ERRORS},
)
async def update_my_profile(
    payload: ProfileUpdate,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    updated = await service.update_profile(current_user, payload, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(updated), message="Profile updated successfully")


# ----------------------------------------------------------------------
# Directory
# ----------------------------------------------------------------------
@router.get(
    "",
    dependencies=[require("users:view")],
    response_model=APIResponse[Page[UserRead]],
    summary="List users",
    description=(
        "Returns a page of users with search, status filtering, organizational filters "
        "and sorting. Search covers the staff code, username, both name parts, the full "
        "name, and the email and mobile fields. Live and archived accounts are never "
        "mixed: pass `archived=true` to see the archive."
    ),
    responses={**_COMMON_ERRORS},
)
async def list_users(
    service: UserSvc,
    current_user: CurrentUser,
    params: Annotated[UserListParams, Query()],
) -> APIResponse[Page[UserRead]]:
    del current_user
    rows, total = await service.list(params)
    page = Page.create(
        [UserRead.from_user(row) for row in rows],
        page=params.page,
        page_size=params.page_size,
        total_items=total,
    )
    return APIResponse.ok(page, message="Users retrieved successfully")


@router.post(
    "",
    dependencies=[require("users:create")],
    response_model=APIResponse[UserRead],
    status_code=status.HTTP_201_CREATED,
    summary="Create a user",
    description=(
        "Provisions an account. The staff code is generated by the database and cannot "
        "be supplied. Email and username are compared case-insensitively, so duplicates "
        "are rejected with 409 rather than stored."
    ),
    responses={**_COMMON_ERRORS, **_CONFLICT},
)
async def create_user(
    payload: UserCreate,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    created = await service.create(payload, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(created), message="User created successfully")


@router.get(
    "/{user_id}",
    dependencies=[require("users:view")],
    response_model=APIResponse[UserRead],
    summary="Get a user",
    responses={**_COMMON_ERRORS, **_NOT_FOUND},
)
async def get_user(
    user_id: uuid.UUID,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    del current_user
    user = await service.get_by_id(user_id)
    return APIResponse.ok(UserRead.from_user(user), message="User retrieved successfully")


@router.patch(
    "/{user_id}",
    dependencies=[require("users:update")],
    response_model=APIResponse[UserRead],
    summary="Update a user",
    description=(
        "Partial update; omitted fields are left unchanged. Passwords are not settable "
        "here -- use the reset endpoint, which is audited separately."
    ),
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def update_user(
    user_id: uuid.UUID,
    payload: UserUpdate,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    updated = await service.update(user_id, payload, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(updated), message="User updated successfully")


# ----------------------------------------------------------------------
# Lifecycle
# ----------------------------------------------------------------------
@router.post(
    "/{user_id}/activate",
    dependencies=[require("users:update")],
    response_model=APIResponse[UserRead],
    summary="Activate a user",
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def activate_user(
    user_id: uuid.UUID,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    user = await service.set_status(user_id, active=True, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(user), message="User activated successfully")


@router.post(
    "/{user_id}/deactivate",
    dependencies=[require("users:update")],
    response_model=APIResponse[UserRead],
    summary="Deactivate a user",
    description=(
        "Blocks sign-in and revokes every active session. Refused for your own account "
        "and for the last active account, either of which would lock everyone out."
    ),
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def deactivate_user(
    user_id: uuid.UUID,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    user = await service.set_status(user_id, active=False, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(user), message="User deactivated successfully")


@router.post(
    "/{user_id}/archive",
    dependencies=[require("users:delete")],
    response_model=APIResponse[UserRead],
    summary="Archive a user",
    description=(
        "Soft deletes the account and revokes its sessions. Refused while other records "
        "still reference the user -- today, any team they manage."
    ),
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def archive_user(
    user_id: uuid.UUID,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    user = await service.archive(user_id, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(user), message="User archived successfully")


@router.post(
    "/{user_id}/restore",
    dependencies=[require("users:delete")],
    response_model=APIResponse[UserRead],
    summary="Restore an archived user",
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def restore_user(
    user_id: uuid.UUID,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    user = await service.restore(user_id, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(user), message="User restored successfully")


@router.post(
    "/{user_id}/reset-password",
    dependencies=[require("users:update")],
    response_model=APIResponse[UserRead],
    summary="Reset a user's password",
    description=(
        "Sets a new password on the user's behalf. By default it also requires them to "
        "choose their own at the next sign-in and revokes their existing sessions, so a "
        "reset performed because of a suspected compromise actually ends it."
    ),
    responses={**_COMMON_ERRORS, **_NOT_FOUND, **_CONFLICT},
)
async def reset_user_password(
    user_id: uuid.UUID,
    payload: AdminPasswordReset,
    service: UserSvc,
    current_user: CurrentUser,
) -> APIResponse[UserRead]:
    user = await service.reset_password(user_id, payload, actor_id=current_user.id)
    return APIResponse.ok(UserRead.from_user(user), message="Password reset successfully")
