"""Unit tests for the user-management validation boundary."""

from __future__ import annotations

from datetime import date, timedelta

import pytest
from pydantic import ValidationError

from app.models.enums import Gender, RecordStatus
from app.schemas.user import (
    AdminPasswordReset,
    ProfileUpdate,
    UserCreate,
    UserListParams,
    UserUpdate,
)

pytestmark = pytest.mark.unit


def payload(**overrides: object) -> dict[str, object]:
    base: dict[str, object] = {
        "first_name": "Jane",
        "last_name": "Doe",
        "username": "jane.doe",
        "email": "Jane.Doe@Example.COM",
        "password": "Str0ng@Pass",
    }
    base.update(overrides)
    return base


class TestUsername:
    def test_is_lower_cased(self) -> None:
        assert UserCreate(**payload(username="Jane.Doe")).username == "jane.doe"

    def test_spaces_become_dots(self) -> None:
        assert UserCreate(**payload(username="jane doe")).username == "jane.doe"

    def test_dots_hyphens_and_underscores_are_allowed(self) -> None:
        assert UserCreate(**payload(username="j.doe-01_x")).username == "j.doe-01_x"

    @pytest.mark.parametrize("username", [".leading", "-leading", "has@at", "has/slash", "has#hash"])
    def test_invalid_characters_are_rejected(self, username: str) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(username=username))

    def test_too_short_is_rejected(self) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(username="ab"))


class TestEmails:
    def test_official_email_is_normalised(self) -> None:
        assert UserCreate(**payload()).email == "jane.doe@example.com"

    def test_personal_email_is_normalised(self) -> None:
        user = UserCreate(**payload(personal_email="  Jane@Personal.Example "))
        assert user.personal_email == "jane@personal.example"

    def test_personal_email_is_optional(self) -> None:
        assert UserCreate(**payload()).personal_email is None

    @pytest.mark.parametrize("email", ["not-an-email", "a@b", "@example.com"])
    def test_a_malformed_official_email_is_rejected(self, email: str) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(email=email))


class TestMobileNumber:
    @pytest.mark.parametrize(
        "number", ["+91 98765 43210", "9876543210", "020 7946 0958", "+1 (555) 123-4567"]
    )
    def test_realistic_formats_are_accepted(self, number: str) -> None:
        assert UserCreate(**payload(phone_number=number)).phone_number is not None

    @pytest.mark.parametrize("number", ["call me", "12", "+", "phone: 999"])
    def test_free_text_is_rejected(self, number: str) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(phone_number=number))

    def test_a_blank_number_becomes_none(self) -> None:
        assert UserCreate(**payload(phone_number="   ")).phone_number is None


class TestDateOfBirth:
    def test_a_realistic_date_is_accepted(self) -> None:
        assert UserCreate(**payload(date_of_birth="1994-06-15")).date_of_birth == date(1994, 6, 15)

    def test_a_future_date_is_rejected(self) -> None:
        tomorrow = (date.today() + timedelta(days=1)).isoformat()
        with pytest.raises(ValidationError):
            UserCreate(**payload(date_of_birth=tomorrow))

    def test_an_implausibly_young_date_is_rejected(self) -> None:
        """Catches the common slip of entering the current year."""
        recent = date.today().replace(year=date.today().year - 5).isoformat()
        with pytest.raises(ValidationError):
            UserCreate(**payload(date_of_birth=recent))

    def test_an_implausibly_old_date_is_rejected(self) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(date_of_birth="1890-01-01"))


class TestCreateDefaults:
    def test_status_defaults_to_active(self) -> None:
        assert UserCreate(**payload()).status is RecordStatus.ACTIVE

    def test_force_password_change_defaults_to_false(self) -> None:
        assert UserCreate(**payload()).force_password_change is False

    def test_gender_is_optional_and_typed(self) -> None:
        assert UserCreate(**payload()).gender is None
        assert UserCreate(**payload(gender="female")).gender is Gender.FEMALE

    def test_an_unknown_gender_is_rejected(self) -> None:
        with pytest.raises(ValidationError):
            UserCreate(**payload(gender="unspecified"))

    def test_organizational_references_are_optional(self) -> None:
        """A user must be creatable before the org tree exists."""
        user = UserCreate(**payload())
        assert user.business_unit_id is None

    def test_a_client_cannot_supply_a_user_code(self) -> None:
        """The staff code is generated by the database and is never an input."""
        with pytest.raises(ValidationError):
            UserCreate(**payload(user_code="USR-000123"))


class TestUserUpdate:
    def test_omitted_fields_are_not_reported_as_set(self) -> None:
        assert UserUpdate(first_name="Jane").model_dump(exclude_unset=True) == {"first_name": "Jane"}

    def test_an_empty_update_is_empty(self) -> None:
        assert UserUpdate().model_dump(exclude_unset=True) == {}

    def test_a_password_cannot_be_set_through_a_general_edit(self) -> None:
        with pytest.raises(ValidationError):
            UserUpdate(password="Str0ng@Pass")

    def test_a_user_code_cannot_be_edited(self) -> None:
        with pytest.raises(ValidationError):
            UserUpdate(user_code="USR-000123")

    def test_an_organizational_reference_can_be_cleared_with_null(self) -> None:
        payload_ = UserUpdate(team_id=None).model_dump(exclude_unset=True)
        assert payload_ == {"team_id": None}


class TestProfileUpdate:
    def test_accepts_the_fields_a_user_owns(self) -> None:
        profile = ProfileUpdate(
            personal_email="jane@personal.example",
            phone_number="+91 98765 43210",
            avatar_url="https://cdn.example/a.png",
        )
        assert profile.personal_email == "jane@personal.example"

    @pytest.mark.parametrize(
        "field",
        [
            "first_name",
            "last_name",
            "username",
            "email",
            "status",
            "is_superuser",
            "business_unit_id",
            "designation_id",
            "user_code",
        ],
    )
    def test_administrative_fields_are_rejected_outright(self, field: str) -> None:
        """Not filtered downstream -- absent from the model, so the request 422s."""
        with pytest.raises(ValidationError):
            ProfileUpdate(**{field: "anything"})


class TestAdminPasswordReset:
    def test_defaults_force_a_change_and_revoke_sessions(self) -> None:
        """A reset is usually a response to a compromise; the safe default matters."""
        reset = AdminPasswordReset(new_password="Str0ng@Pass")
        assert reset.force_password_change is True
        assert reset.revoke_sessions is True

    def test_a_weak_password_is_rejected(self) -> None:
        with pytest.raises(ValidationError):
            AdminPasswordReset(new_password="weak")


class TestUserListParams:
    def test_defaults(self) -> None:
        params = UserListParams()
        assert params.page == 1
        assert params.archived is False
        assert params.business_unit_id is None

    def test_organizational_filters_are_accepted(self) -> None:
        params = UserListParams(business_unit_id="0f9c1d2e-3a4b-5c6d-7e8f-9a0b1c2d3e4f")
        assert params.business_unit_id is not None

    def test_an_unknown_filter_is_rejected(self) -> None:
        with pytest.raises(ValidationError):
            UserListParams(bogus="1")
