"""Reusable SQLAlchemy column mixins.

Every table in the platform composes these mixins so that the audit story is
identical everywhere:

* :class:`UUIDPrimaryKeyMixin` -- UUID surrogate key generated by the database.
* :class:`TimestampMixin`      -- ``created_at`` / ``updated_at``.
* :class:`AuditMixin`          -- ``created_by`` / ``updated_by``.
* :class:`SoftDeleteMixin`     -- ``deleted_at`` / ``deleted_by``.

New feature modules should inherit :class:`app.db.base_class.Base` together with
:class:`AuditableBase` rather than redeclaring these columns.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, declarative_mixin, declared_attr, mapped_column


def _actor_fk() -> ForeignKey:
    """The foreign key every audit column uses to point at ``users``.

    ``ondelete="SET NULL"`` because removing a user must not cascade into
    deleting the records they touched.

    ``use_alter`` because these columns close a dependency cycle: every table
    points back at ``users``, and ``users`` in turn points at the organization
    masters. Without it SQLAlchemy cannot sort the tables, and responds by
    discarding *every* foreign key between the tables involved -- which would
    silently mis-order a future autogenerated migration. It changes how the DDL
    is sequenced, not the constraint itself.

    A fresh :class:`ForeignKey` per call: a single shared instance cannot be
    attached to more than one column.
    """
    return ForeignKey("users.id", ondelete="SET NULL", use_alter=True)


@declarative_mixin
class UUIDPrimaryKeyMixin:
    """UUID primary key generated by PostgreSQL (``gen_random_uuid()``)."""

    id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
        doc="Surrogate primary key.",
    )


@declarative_mixin
class TimestampMixin:
    """Creation and last-modification timestamps, maintained by the database."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        doc="UTC timestamp of row creation.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        onupdate=text("now()"),
        doc="UTC timestamp of the last update.",
    )


@declarative_mixin
class AuditMixin:
    """Identifies the user responsible for the last write."""

    @declared_attr
    @classmethod
    def created_by(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(
            PGUUID(as_uuid=True),
            _actor_fk(),
            nullable=True,
            doc="User who created the row; NULL for system-generated rows.",
        )

    @declared_attr
    @classmethod
    def updated_by(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(
            PGUUID(as_uuid=True),
            _actor_fk(),
            nullable=True,
            doc="User who last updated the row.",
        )


@declarative_mixin
class SoftDeleteMixin:
    """Soft delete support.

    Rows are never physically removed by application code. Repositories filter
    ``deleted_at IS NULL`` by default; pass ``include_deleted=True`` to opt in
    to archived rows.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
        doc="UTC timestamp of soft deletion; NULL means the row is active.",
    )

    @declared_attr
    @classmethod
    def deleted_by(cls) -> Mapped[uuid.UUID | None]:
        return mapped_column(
            PGUUID(as_uuid=True),
            _actor_fk(),
            nullable=True,
            doc="User who soft deleted the row.",
        )

    @property
    def is_deleted(self) -> bool:
        """``True`` when the row has been soft deleted."""
        return self.deleted_at is not None


class AuditableBase(UUIDPrimaryKeyMixin, TimestampMixin, AuditMixin, SoftDeleteMixin):
    """Convenience composition applied to every table in the platform."""

    __abstract__ = True
