"""Employee master

Adds the five tables of the Employee Management module:

* ``employees``                    -- the central record
* ``employee_addresses``           -- current and permanent
* ``employee_bank_details``        -- sensitive
* ``employee_identification``      -- sensitive
* ``employee_employment_history``  -- append-only placement history

All five are new, so there is no backfill: this revision is a pure create and
its downgrade is a clean drop.

The one thing autogenerate cannot see is the sequence behind ``employee_code``,
which the column default calls. It is created before the table that depends on
it and dropped after that table is gone.

Revision ID: 0004_employee_master
Revises: 0003_user_management
Created: 2026-08-03 08:34:04.814880+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0004_employee_master'
down_revision: str | None = '0003_user_management'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Kept in step with app.models.employee.EMPLOYEE_CODE_SEQUENCE. Spelled out
#: here rather than imported: a migration must keep working against the schema
#: it was written for, even after the model moves on.
EMPLOYEE_CODE_SEQUENCE = "employees_employee_code_seq"


def upgrade() -> None:
    """Apply the schema change."""
    # The column default calls nextval() on this, so it has to exist first.
    op.execute(sa.text(f"CREATE SEQUENCE IF NOT EXISTS {EMPLOYEE_CODE_SEQUENCE} AS bigint START WITH 1"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=20), server_default=sa.text("'EMP-' || lpad(nextval('employees_employee_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('blood_group', sa.String(length=3), nullable=True),
    sa.Column('marital_status', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('personal_email', sa.String(length=320), nullable=True),
    sa.Column('mobile_number', sa.String(length=32), nullable=True),
    sa.Column('alternate_number', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=150), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('official_email', sa.String(length=320), nullable=False),
    sa.Column('official_mobile', sa.String(length=32), nullable=True),
    sa.Column('extension_number', sa.String(length=20), nullable=True),
    sa.Column('work_mode', sa.String(length=20), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('confirmation_date', sa.Date(), nullable=True),
    sa.Column('employment_type_id', sa.UUID(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('practice_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('work_location_id', sa.UUID(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('shift_id', sa.UUID(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), server_default='probation', nullable=False),
    sa.Column('ctc', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_grade_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("blood_group IS NULL OR blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')", name=op.f('ck_employees_blood_group')),
    sa.CheckConstraint("employment_status IN ('probation', 'confirmed', 'active', 'notice_period', 'resigned', 'inactive')", name=op.f('ck_employees_employment_status')),
    sa.CheckConstraint("gender IS NULL OR gender IN ('male', 'female', 'other', 'prefer_not_to_say')", name=op.f('ck_employees_gender')),
    sa.CheckConstraint("marital_status IS NULL OR marital_status IN ('single', 'married', 'divorced', 'widowed', 'separated')", name=op.f('ck_employees_marital_status')),
    sa.CheckConstraint("work_mode IS NULL OR work_mode IN ('office', 'remote', 'hybrid')", name=op.f('ck_employees_work_mode')),
    sa.CheckConstraint('ctc IS NULL OR ctc >= 0', name=op.f('ck_employees_ctc_non_negative')),
    sa.CheckConstraint('reporting_manager_id IS NULL OR reporting_manager_id <> id', name=op.f('ck_employees_manager_not_self')),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_units.id'], name=op.f('fk_employees_business_unit_id_business_units'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employees_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_employees_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employees_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], name=op.f('fk_employees_designation_id_designations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employment_type_id'], ['employment_types.id'], name=op.f('fk_employees_employment_type_id_employment_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_employees_grade_id_grades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], name=op.f('fk_employees_practice_id_practices'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], name=op.f('fk_employees_reporting_manager_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salary_grade_id'], ['grades.id'], name=op.f('fk_employees_salary_grade_id_grades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_employees_team_id_teams'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_employees_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employees_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_location_id'], ['locations.id'], name=op.f('fk_employees_work_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    comment='Employee master record; the central entity of the HRMS.'
    )
    op.create_index(op.f('ix_employees_business_unit_id'), 'employees', ['business_unit_id'], unique=False)
    op.create_index(op.f('ix_employees_deleted_at'), 'employees', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_employment_type_id'), 'employees', ['employment_type_id'], unique=False)
    op.create_index(op.f('ix_employees_grade_id'), 'employees', ['grade_id'], unique=False)
    op.create_index(op.f('ix_employees_joining_date'), 'employees', ['joining_date'], unique=False)
    op.create_index('ix_employees_name', 'employees', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_employees_official_email'), 'employees', ['official_email'], unique=False)
    op.create_index('ix_employees_placement', 'employees', ['business_unit_id', 'department_id', 'designation_id'], unique=False)
    op.create_index(op.f('ix_employees_practice_id'), 'employees', ['practice_id'], unique=False)
    op.create_index(op.f('ix_employees_reporting_manager_id'), 'employees', ['reporting_manager_id'], unique=False)
    op.create_index(op.f('ix_employees_salary_grade_id'), 'employees', ['salary_grade_id'], unique=False)
    op.create_index('ix_employees_status_deleted_at', 'employees', ['employment_status', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_employees_team_id'), 'employees', ['team_id'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=True)
    op.create_index(op.f('ix_employees_work_location_id'), 'employees', ['work_location_id'], unique=False)
    op.create_index('uq_employees_official_email_lower', 'employees', [sa.literal_column('lower(official_email)')], unique=True)
    op.create_table('employee_addresses',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("address_type IN ('current', 'permanent')", name=op.f('ck_employee_addresses_address_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_addresses_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_employee_addresses_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_addresses_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_employee_addresses_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_addresses')),
    comment='Current and permanent addresses of an employee.'
    )
    op.create_index(op.f('ix_employee_addresses_deleted_at'), 'employee_addresses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_addresses_employee_id'), 'employee_addresses', ['employee_id'], unique=False)
    op.create_index('uq_employee_addresses_employee_id_type', 'employee_addresses', ['employee_id', 'address_type'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('employee_bank_details',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('account_number', sa.String(length=34), nullable=False),
    sa.Column('account_holder_name', sa.String(length=150), nullable=True),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('branch_name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_bank_details_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_employee_bank_details_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_bank_details_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_employee_bank_details_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_bank_details')),
    comment='Bank account an employee is paid into. Sensitive.'
    )
    op.create_index(op.f('ix_employee_bank_details_deleted_at'), 'employee_bank_details', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_bank_details_employee_id'), 'employee_bank_details', ['employee_id'], unique=False)
    op.create_index('uq_employee_bank_details_employee_id', 'employee_bank_details', ['employee_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_table('employee_employment_history',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('change_type', sa.String(length=30), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('work_location_id', sa.UUID(), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('employment_status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("change_type IN ('created', 'confirmation', 'promotion', 'department_transfer', 'designation_change', 'grade_change', 'manager_change', 'location_change', 'status_change', 'details_updated')", name=op.f('ck_employee_employment_history_change_type')),
    sa.CheckConstraint("employment_status IN ('probation', 'confirmed', 'active', 'notice_period', 'resigned', 'inactive')", name=op.f('ck_employee_employment_history_employment_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_employment_history_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_employee_employment_history_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_employee_employment_history_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], name=op.f('fk_employee_employment_history_designation_id_designations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_employment_history_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], name=op.f('fk_employee_employment_history_grade_id_grades'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], name=op.f('fk_employee_employment_history_reporting_manager_id_employees'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_employee_employment_history_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_location_id'], ['locations.id'], name=op.f('fk_employee_employment_history_work_location_id_locations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_employment_history')),
    comment="Append-only history of an employee's organizational placement."
    )
    op.create_index(op.f('ix_employee_employment_history_change_type'), 'employee_employment_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_deleted_at'), 'employee_employment_history', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_department_id'), 'employee_employment_history', ['department_id'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_designation_id'), 'employee_employment_history', ['designation_id'], unique=False)
    op.create_index('ix_employee_employment_history_employee_effective', 'employee_employment_history', ['employee_id', 'effective_date'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_employee_id'), 'employee_employment_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_grade_id'), 'employee_employment_history', ['grade_id'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_reporting_manager_id'), 'employee_employment_history', ['reporting_manager_id'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_work_location_id'), 'employee_employment_history', ['work_location_id'], unique=False)
    op.create_table('employee_identification',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('passport_number', sa.String(length=20), nullable=True),
    sa.Column('passport_expiry', sa.String(length=10), nullable=True),
    sa.Column('driving_license_number', sa.String(length=25), nullable=True),
    sa.Column('uan_number', sa.String(length=12), nullable=True),
    sa.Column('pf_number', sa.String(length=30), nullable=True),
    sa.Column('esi_number', sa.String(length=17), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_employee_identification_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_employee_identification_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_identification_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_employee_identification_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_identification')),
    comment='Government-issued identifiers for an employee. Sensitive.'
    )
    op.create_index(op.f('ix_employee_identification_deleted_at'), 'employee_identification', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_employee_identification_employee_id'), 'employee_identification', ['employee_id'], unique=False)
    op.create_index('uq_employee_identification_aadhaar', 'employee_identification', [sa.literal_column('upper(aadhaar_number)')], unique=True, postgresql_where=sa.text('aadhaar_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_employee_identification_employee_id', 'employee_identification', ['employee_id'], unique=True, postgresql_where='deleted_at IS NULL')
    op.create_index('uq_employee_identification_esi', 'employee_identification', [sa.literal_column('upper(esi_number)')], unique=True, postgresql_where=sa.text('esi_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_employee_identification_pan', 'employee_identification', [sa.literal_column('upper(pan_number)')], unique=True, postgresql_where=sa.text('pan_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_employee_identification_passport', 'employee_identification', [sa.literal_column('upper(passport_number)')], unique=True, postgresql_where=sa.text('passport_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_employee_identification_pf', 'employee_identification', [sa.literal_column('upper(pf_number)')], unique=True, postgresql_where=sa.text('pf_number IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_employee_identification_uan', 'employee_identification', [sa.literal_column('upper(uan_number)')], unique=True, postgresql_where=sa.text('uan_number IS NOT NULL AND deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employee_identification_uan', table_name='employee_identification', postgresql_where=sa.text('uan_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_employee_identification_pf', table_name='employee_identification', postgresql_where=sa.text('pf_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_employee_identification_passport', table_name='employee_identification', postgresql_where=sa.text('passport_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_employee_identification_pan', table_name='employee_identification', postgresql_where=sa.text('pan_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_employee_identification_esi', table_name='employee_identification', postgresql_where=sa.text('esi_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index('uq_employee_identification_employee_id', table_name='employee_identification', postgresql_where='deleted_at IS NULL')
    op.drop_index('uq_employee_identification_aadhaar', table_name='employee_identification', postgresql_where=sa.text('aadhaar_number IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_employee_identification_employee_id'), table_name='employee_identification')
    op.drop_index(op.f('ix_employee_identification_deleted_at'), table_name='employee_identification')
    op.drop_table('employee_identification')
    op.drop_index(op.f('ix_employee_employment_history_work_location_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_reporting_manager_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_grade_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_employee_id'), table_name='employee_employment_history')
    op.drop_index('ix_employee_employment_history_employee_effective', table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_designation_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_department_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_deleted_at'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_change_type'), table_name='employee_employment_history')
    op.drop_table('employee_employment_history')
    op.drop_index('uq_employee_bank_details_employee_id', table_name='employee_bank_details', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_employee_bank_details_employee_id'), table_name='employee_bank_details')
    op.drop_index(op.f('ix_employee_bank_details_deleted_at'), table_name='employee_bank_details')
    op.drop_table('employee_bank_details')
    op.drop_index('uq_employee_addresses_employee_id_type', table_name='employee_addresses', postgresql_where='deleted_at IS NULL')
    op.drop_index(op.f('ix_employee_addresses_employee_id'), table_name='employee_addresses')
    op.drop_index(op.f('ix_employee_addresses_deleted_at'), table_name='employee_addresses')
    op.drop_table('employee_addresses')
    op.drop_index('uq_employees_official_email_lower', table_name='employees')
    op.drop_index(op.f('ix_employees_work_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_team_id'), table_name='employees')
    op.drop_index('ix_employees_status_deleted_at', table_name='employees')
    op.drop_index(op.f('ix_employees_salary_grade_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_reporting_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_practice_id'), table_name='employees')
    op.drop_index('ix_employees_placement', table_name='employees')
    op.drop_index(op.f('ix_employees_official_email'), table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_index(op.f('ix_employees_joining_date'), table_name='employees')
    op.drop_index(op.f('ix_employees_grade_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_type_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_deleted_at'), table_name='employees')
    op.drop_index(op.f('ix_employees_business_unit_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###

    # After the table, because the column default depends on it.
    op.execute(sa.text(f"DROP SEQUENCE IF EXISTS {EMPLOYEE_CODE_SEQUENCE}"))
