"""Document vault

Adds the four tables of the Document Management module:

* ``document_categories`` / ``document_types``  -- configurable masters
* ``documents``                                  -- one logical document
* ``document_versions``                          -- append-only uploaded files

All four are new, so there is no backfill.

Two things autogenerate cannot see:

* the sequence behind ``document_code``, which the column default calls;
* the fact that ``documents`` and ``document_versions`` reference each other.
  The pointer from a document to its current version is therefore added with
  ALTER once both tables exist, and dropped before either goes away.

Revision ID: 0005_document_vault
Revises: 0004_employee_master
Created: 2026-08-04 05:41:13.965641+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005_document_vault'
down_revision: str | None = '0004_employee_master'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Kept in step with app.models.document.DOCUMENT_CODE_SEQUENCE. Spelled out
#: here rather than imported: a migration must keep working against the schema
#: it was written for, even after the model moves on.
DOCUMENT_CODE_SEQUENCE = "documents_document_code_seq"

#: The pointer from a document to its newest version. Added by ALTER because
#: the two tables reference each other and neither can be created second.
CURRENT_VERSION_FK = "fk_documents_current_version_id_document_versions"


def upgrade() -> None:
    """Apply the schema change."""
    # The document_code column default calls nextval() on this.
    op.execute(sa.text(f"CREATE SEQUENCE IF NOT EXISTS {DOCUMENT_CODE_SEQUENCE} AS bigint START WITH 1"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('display_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_document_categories_status')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_categories_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_document_categories_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_document_categories_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_categories')),
    comment='Configurable groupings of document types.'
    )
    op.create_index(op.f('ix_document_categories_code'), 'document_categories', ['code'], unique=False)
    op.create_index(op.f('ix_document_categories_deleted_at'), 'document_categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_categories_display_order'), 'document_categories', ['display_order'], unique=False)
    op.create_index(op.f('ix_document_categories_name'), 'document_categories', ['name'], unique=False)
    op.create_index(op.f('ix_document_categories_status'), 'document_categories', ['status'], unique=False)
    op.create_index('uq_document_categories_code_lower', 'document_categories', [sa.literal_column('lower(code)')], unique=True)
    op.create_index('uq_document_categories_name_lower', 'document_categories', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('document_types',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('requires_expiry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allowed_extensions', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_document_types_status')),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], name=op.f('fk_document_types_category_id_document_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_types_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_document_types_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_document_types_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_types')),
    comment='Configurable document types, each belonging to a category.'
    )
    op.create_index(op.f('ix_document_types_category_id'), 'document_types', ['category_id'], unique=False)
    op.create_index(op.f('ix_document_types_code'), 'document_types', ['code'], unique=False)
    op.create_index(op.f('ix_document_types_deleted_at'), 'document_types', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_types_name'), 'document_types', ['name'], unique=False)
    op.create_index(op.f('ix_document_types_status'), 'document_types', ['status'], unique=False)
    op.create_index('uq_document_types_category_id_name_lower', 'document_types', [sa.literal_column('category_id'), sa.literal_column('lower(name)')], unique=True)
    op.create_index('uq_document_types_code_lower', 'document_types', [sa.literal_column('lower(code)')], unique=True)
    op.create_table('documents',
    sa.Column('document_code', sa.String(length=20), server_default=sa.text("'DOC-' || lpad(nextval('documents_document_code_seq')::text, 6, '0')"), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('document_type_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='uploaded', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('version_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("owner_type IN ('employee', 'candidate', 'organization', 'user')", name=op.f('ck_documents_owner_type')),
    sa.CheckConstraint("status IN ('uploaded', 'under_review', 'approved', 'rejected', 'expired', 'archived')", name=op.f('ck_documents_status')),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], name=op.f('fk_documents_category_id_document_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_documents_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], name=op.f('fk_documents_document_type_id_document_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_documents_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_documents_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    comment='A document belonging to an employee, candidate, organization or user.'
    )
    op.create_index(op.f('ix_documents_category_id'), 'documents', ['category_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_code'), 'documents', ['document_code'], unique=True)
    op.create_index(op.f('ix_documents_document_type_id'), 'documents', ['document_type_id'], unique=False)
    op.create_index('ix_documents_expiry_date', 'documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_index('ix_documents_owner', 'documents', ['owner_type', 'owner_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index('ix_documents_status_deleted_at', 'documents', ['status', 'deleted_at'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_document_versions_size_positive')),
    sa.CheckConstraint('version_number >= 1', name=op.f('ck_document_versions_version_number_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_document_versions_deleted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_document_versions_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    comment='Append-only versions of a document. One row per uploaded file.'
    )
    op.create_index('ix_document_versions_checksum', 'document_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_document_versions_deleted_at'), 'document_versions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_index('uq_document_versions_document_id_version', 'document_versions', ['document_id', 'version_number'], unique=True)
    # ### end Alembic commands ###

    # Both tables now exist, so the cycle can be closed.
    op.create_foreign_key(
        CURRENT_VERSION_FK,
        "documents",
        "document_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    """Revert the schema change."""
    # Break the cycle before either table is dropped.
    op.drop_constraint(CURRENT_VERSION_FK, "documents", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_document_versions_document_id_version', table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_index(op.f('ix_document_versions_deleted_at'), table_name='document_versions')
    op.drop_index('ix_document_versions_checksum', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_documents_status_deleted_at', table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index('ix_documents_owner', table_name='documents')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_index('ix_documents_expiry_date', table_name='documents')
    op.drop_index(op.f('ix_documents_document_type_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_code'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_category_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('uq_document_types_code_lower', table_name='document_types')
    op.drop_index('uq_document_types_category_id_name_lower', table_name='document_types')
    op.drop_index(op.f('ix_document_types_status'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_name'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_deleted_at'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_code'), table_name='document_types')
    op.drop_index(op.f('ix_document_types_category_id'), table_name='document_types')
    op.drop_table('document_types')
    op.drop_index('uq_document_categories_name_lower', table_name='document_categories')
    op.drop_index('uq_document_categories_code_lower', table_name='document_categories')
    op.drop_index(op.f('ix_document_categories_status'), table_name='document_categories')
    op.drop_index(op.f('ix_document_categories_name'), table_name='document_categories')
    op.drop_index(op.f('ix_document_categories_display_order'), table_name='document_categories')
    op.drop_index(op.f('ix_document_categories_deleted_at'), table_name='document_categories')
    op.drop_index(op.f('ix_document_categories_code'), table_name='document_categories')
    op.drop_table('document_categories')
    # ### end Alembic commands ###

    # After the table whose default depended on it.
    op.execute(sa.text(f"DROP SEQUENCE IF EXISTS {DOCUMENT_CODE_SEQUENCE}"))
