"""Role-based access control: roles, permissions and assignments.

Revision ID: 0015_rbac
Revises: 0014_workforce_operations

Written by hand rather than left as autogenerated output. Autogenerate also
picked up the pre-existing drift between the raw-SQL migrations (0007 onwards)
and the models -- index and constraint renames across recruitment, requisitions
and talent pools. Folding unrelated rewrites of nine other tables into an RBAC
migration would make this one impossible to review and impossible to roll back
cleanly, so only the four new tables are here.

Every ``use_alter=True`` autogenerate produced has been stripped: inside
``op.create_table`` SQLAlchemy silently *skips* the constraint, which has cost
this project three rounds of missing foreign keys already.

The seed imports ``app.core.permissions``. That is a deliberate exception to the
usual rule that a migration should not import application code: the permission
catalogue is a mirror of that registry by definition, and duplicating 72 literals
here would guarantee the two drift. The service layer reconciles the table to the
registry on demand, so a fresh database and a long-lived one converge either way.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.permissions import GROUP_LABELS, MODULES, SYSTEM_ROLES, code

revision: str = "0015_rbac"
down_revision: str | None = "0014_workforce_operations"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Dropped in reverse dependency order.
_TABLES = ("user_roles", "role_permissions", "roles", "permissions")


def upgrade() -> None:
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("module", sa.String(length=40), nullable=False),
        # 40, not 20: this migration seeds from the *live* registry, so the
        # column must hold the longest action the registry will ever grow —
        # "employee_settings_update" arrived with payroll Phase 2. Databases
        # created before then are widened by 0025.
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("permission_group", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_permissions_created_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], name=op.f("fk_permissions_deleted_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_permissions_updated_by_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name="uq_permissions_code"),
        comment="The permission catalogue, reconciled from app.core.permissions.",
    )
    op.create_index(op.f("ix_permissions_code"), "permissions", ["code"], unique=False)
    op.create_index(op.f("ix_permissions_deleted_at"), "permissions", ["deleted_at"], unique=False)
    op.create_index("ix_permissions_group_module", "permissions", ["permission_group", "module"], unique=False)
    op.create_index(op.f("ix_permissions_module"), "permissions", ["module"], unique=False)
    op.create_index(op.f("ix_permissions_permission_group"), "permissions", ["permission_group"], unique=False)

    op.create_table(
        "roles",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.CheckConstraint("char_length(trim(name)) > 0", name=op.f("ck_roles_name_not_blank")),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_roles_created_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], name=op.f("fk_roles_deleted_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_roles_updated_by_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("key", name="uq_roles_key"),
        comment="System and custom roles.",
    )
    op.create_index(op.f("ix_roles_deleted_at"), "roles", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_roles_is_system"), "roles", ["is_system"], unique=False)
    op.create_index(op.f("ix_roles_key"), "roles", ["key"], unique=False)
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=False)
    op.create_index(op.f("ix_roles_status"), "roles", ["status"], unique=False)

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_role_permissions_created_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], name=op.f("fk_role_permissions_deleted_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], name=op.f("fk_role_permissions_permission_id_permissions"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_role_permissions_updated_by_users"), ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "permission_id", name="uq_role_permissions_pair"),
        comment="Which permissions a role grants.",
    )
    op.create_index(op.f("ix_role_permissions_deleted_at"), "role_permissions", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_role_permissions_permission_id"), "role_permissions", ["permission_id"], unique=False)
    op.create_index(op.f("ix_role_permissions_role_id"), "role_permissions", ["role_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("scope_business_unit_id", sa.UUID(), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_user_roles_created_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["deleted_by"], ["users.id"], name=op.f("fk_user_roles_deleted_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["scope_business_unit_id"], ["business_units.id"], name=op.f("fk_user_roles_scope_business_unit_id_business_units"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], name=op.f("fk_user_roles_updated_by_users"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role_id", "scope_business_unit_id", name="uq_user_roles_grant"),
        comment="Role assignments, optionally scoped to a business unit.",
    )
    op.create_index(op.f("ix_user_roles_deleted_at"), "user_roles", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_scope_business_unit_id"), "user_roles", ["scope_business_unit_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.create_index("ix_user_roles_user_role", "user_roles", ["user_id", "role_id"], unique=False)
    # NULLs are distinct in a unique constraint, so uq_user_roles_grant does not
    # stop the same unscoped role being granted twice. This covers that case.
    op.create_index(
        "uq_user_roles_unscoped",
        "user_roles",
        ["user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("scope_business_unit_id IS NULL"),
    )

    _seed()


def _seed() -> None:
    """Fill the catalogue, the eight shipped roles, and their grants."""
    for module in MODULES:
        for action in module.actions:
            op.execute(
                sa.text(
                    "INSERT INTO permissions(code, module, action, permission_group, label, description)"
                    " VALUES (:code, :module, :action, :grp, :label, :description)"
                ).bindparams(
                    code=code(module.key, action),
                    module=module.key,
                    action=action.value,
                    grp=module.group.value,
                    label=f"{action.value.title()} {module.label.lower()}",
                    description=module.description,
                )
            )

    for role in SYSTEM_ROLES:
        op.execute(
            sa.text(
                "INSERT INTO roles(key, name, description, is_system)"
                " VALUES (:key, :name, :description, true)"
            ).bindparams(key=role.key, name=role.name, description=role.description)
        )
        # Joined on the code rather than carrying ids around: the insert above
        # generated them server-side, and re-reading is cheaper than threading
        # a lookup table through the seeder.
        op.execute(
            sa.text(
                "INSERT INTO role_permissions(role_id, permission_id)"
                " SELECT r.id, p.id FROM roles r, permissions p"
                " WHERE r.key = :key AND p.code = ANY(:codes)"
            ).bindparams(key=role.key, codes=list(role.permissions))
        )

    # Existing superusers keep working: they are granted Super Admin so that the
    # very first deploy of RBAC does not lock the only administrator out.
    op.execute(
        sa.text(
            "INSERT INTO user_roles(user_id, role_id, granted_at)"
            " SELECT u.id, r.id, now() FROM users u, roles r"
            " WHERE r.key = 'super_admin' AND u.is_superuser = true AND u.deleted_at IS NULL"
        )
    )
    # Everyone else gets the Employee floor. An account with no role at all
    # cannot use the product, and fixing that in a hurry is how a second
    # superuser gets created.
    op.execute(
        sa.text(
            "INSERT INTO user_roles(user_id, role_id, granted_at)"
            " SELECT u.id, r.id, now() FROM users u, roles r"
            " WHERE r.key = 'employee' AND u.is_superuser = false AND u.deleted_at IS NULL"
        )
    )


def downgrade() -> None:
    for table in _TABLES:
        op.drop_table(table)
