"""Pydantic v2 schemas -- the validation boundary of the API."""

from app.schemas.auth import (
    ChangePasswordRequest,
    ForgotPasswordRequest,
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    PasswordResetIssued,
    RefreshRequest,
    ResetPasswordRequest,
    TokenPair,
)
from app.schemas.business_unit import BusinessUnitCreate, BusinessUnitRead, BusinessUnitUpdate
from app.schemas.common import (
    APIErrorResponse,
    APIResponse,
    ErrorDetail,
    MessageData,
    Page,
    PageMeta,
    PaginationParams,
)
from app.schemas.designation import (
    DesignationCreate,
    DesignationListParams,
    DesignationRead,
    DesignationUpdate,
)
from app.schemas.employment_type import (
    EmploymentTypeCreate,
    EmploymentTypeRead,
    EmploymentTypeUpdate,
)
from app.schemas.grade import GradeCreate, GradeRead, GradeUpdate
from app.schemas.health import DependencyCheck, HealthStatus, ReadinessStatus
from app.schemas.location import LocationCreate, LocationRead, LocationUpdate
from app.schemas.masters import (
    CodedMasterCreateBase,
    CodedMasterReadBase,
    CodedMasterUpdateBase,
    MasterCreateBase,
    MasterListParams,
    MasterReadBase,
    MasterSummary,
    MasterUpdateBase,
    SortOrder,
)
from app.schemas.organization import OrganizationCreate, OrganizationRead, OrganizationUpdate
from app.schemas.team import TeamCreate, TeamListParams, TeamRead, TeamUpdate
from app.schemas.user import (
    AdminPasswordReset,
    ProfileUpdate,
    UserCreate,
    UserListParams,
    UserOrganization,
    UserRead,
    UserSummary,
    UserUpdate,
)

__all__ = [
    "APIErrorResponse",
    "APIResponse",
    "AdminPasswordReset",
    "BusinessUnitCreate",
    "BusinessUnitRead",
    "BusinessUnitUpdate",
    "ChangePasswordRequest",
    "CodedMasterCreateBase",
    "CodedMasterReadBase",
    "CodedMasterUpdateBase",
    "DependencyCheck",
    "DesignationCreate",
    "DesignationListParams",
    "DesignationRead",
    "DesignationUpdate",
    "EmploymentTypeCreate",
    "EmploymentTypeRead",
    "EmploymentTypeUpdate",
    "ErrorDetail",
    "ForgotPasswordRequest",
    "GradeCreate",
    "GradeRead",
    "GradeUpdate",
    "HealthStatus",
    "LocationCreate",
    "LocationRead",
    "LocationUpdate",
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "MasterCreateBase",
    "MasterListParams",
    "MasterReadBase",
    "MasterSummary",
    "MasterUpdateBase",
    "MessageData",
    "OrganizationCreate",
    "OrganizationRead",
    "OrganizationUpdate",
    "Page",
    "PageMeta",
    "PaginationParams",
    "PasswordResetIssued",
    "ProfileUpdate",
    "ReadinessStatus",
    "RefreshRequest",
    "ResetPasswordRequest",
    "SortOrder",
    "TeamCreate",
    "TeamListParams",
    "TeamRead",
    "TeamUpdate",
    "TokenPair",
    "UserCreate",
    "UserListParams",
    "UserOrganization",
    "UserRead",
    "UserSummary",
    "UserUpdate",
]
